apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-nginx-deployment-2
  labels:
    app: nginx-webapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-webapp2
  template:
    metadata:
      labels:
        app: nginx-webapp2
    spec:
      containers:
      - name: nginx
        image: nginx:1.28  
       
